USE `dulumary`;

CREATE TABLE `review`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `store` VARCHAR(8) NOT NULL,
    `menu` VARCHAR(8) NOT NULL,
    `point` DECIMAL(2,1) DEFAULT 3.5,
    `review` VARCHAR(256),
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DESC `review`;

ALTER TABLE `review` ADD COLUMN `userName` VARCHAR(32) NOT NULL AFTER `menu`;

ALTER TABLE `review` MODIFY COLUMN `store` VARCHAR(32) NOT NULL;

ALTER TABLE `review` MODIFY COLUMN `menu` VARCHAR(32) NOT NULL;

ALTER TABLE `review` CHANGE COLUMN `store` `storeName` VARCHAR(32) NOT NULL;

DROP TABLE `review`;